plugins {
    id 'java'
    id "checkstyle"
}

group = 'io.github.lengors'

String javaVersion = properties["javaVersion"] ?: "25"
String checkstyleToolVersion = properties["checkstyleToolVersion"] ?: "10.23.1"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(javaVersion)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
    mavenLocal()
}

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

tasks.named('test') { Test it ->
    it.useJUnitPlatform()
}

checkstyle {
    toolVersion = checkstyleToolVersion
}
