# Versions
wireMockTestcontainersVersion=1.0-alpha-15
springDependencyManagementVersion=1.1.7
checkerframeworkPluginVersion=1.0.2
checkstyleToolVersion=10.23.1
checkerframeworkVersion=4.2.0
sonarqubeVersion=7.3.1.8318
springBootVersion=4.0.6
javaVersion=25
version=0.0.0-local.0

# Compilation settings
org.gradle.parallel=true